Fix

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -42,28 +42,38 @@ jobs:
             echo "Virtual machines exist"
             exit 1
           else
-            echo "No virtual machines found. Creating..."
-            # Deploy the Server
-            json=$(curl -s --location 'https://marketplace.tensordock.com/api/v0/client/deploy/single' \
-              --data-urlencode "api_key=$API_KEY" \
-              --data-urlencode "api_token=$API_TOKEN" \
-              --data-urlencode "name=Rigg" \
-              --data-urlencode "gpu_count=0" \
-              --data-urlencode "vcpus=$CPU_AMOUNT" \
-              --data-urlencode "ram=$RAM_AMOUNT" \
-              --data-urlencode "external_ports={$FIRST_PORT}" \
-              --data-urlencode "internal_ports={22}" \
-              --data-urlencode "hostnode=$HOSTNODE_ID" \
-              --data-urlencode "storage=$STORAGE_AMOUNT" \
-              --data-urlencode "operating_system=Ubuntu 20.04 LTS" \
-              --data-urlencode "cloudinit_script=runcmd:\n - docker run -d --restart unless-stopped -e REPO_URL=https://github.com/LesVu/aosp_buildscript -e ACCESS_TOKEN=$PAT_TOKEN -e RUNNER_NAME=aosp-builder -e LABELS=aosp-builder -e RUNNER_WORKDIR=/runner/work -e RUN_AS_ROOT=false -v /var/run/docker.sock:/var/run/docker.sock -v /runner:/runner --name aosp-builder myoung34/github-runner:ubuntu-focal")
+            # IF HOSTNODE_ID IS NOT EMPTY
+            if [ -n "$HOSTNODE_ID" ]; then
+              echo "No virtual machines found. Creating..."
+              # Deploy the Server
+              json=$(curl -s --location 'https://marketplace.tensordock.com/api/v0/client/deploy/single' \
+                --data-urlencode "api_key=$API_KEY" \
+                --data-urlencode "api_token=$API_TOKEN" \
+                --data-urlencode "name=Rigg" \
+                --data-urlencode "gpu_count=0" \
+                --data-urlencode "vcpus=$CPU_AMOUNT" \
+                --data-urlencode "ram=$RAM_AMOUNT" \
+                --data-urlencode "external_ports={$FIRST_PORT}" \
+                --data-urlencode "internal_ports={22}" \
+                --data-urlencode "hostnode=$HOSTNODE_ID" \
+                --data-urlencode "storage=$STORAGE_AMOUNT" \
+                --data-urlencode "operating_system=Ubuntu 20.04 LTS" \
+                --data-urlencode "cloudinit_script=runcmd:\n - docker run -d --restart unless-stopped -e REPO_URL=https://github.com/LesVu/aosp_buildscript -e ACCESS_TOKEN=$PAT_TOKEN -e RUNNER_NAME=aosp-builder -e LABELS=aosp-builder -e RUNNER_WORKDIR=/runner/work -e RUN_AS_ROOT=false -v /var/run/docker.sock:/var/run/docker.sock -v /runner:/runner --name aosp-builder myoung34/github-runner:ubuntu-focal")
+            else
+              echo "No Machine available"
+              exit 1
+            fi
           fi
 
+          if [ "$(echo "$json" | jq -r '.success')" = "false" ]; then
+            echo "Failed to create server"
+            exit 1
+          fi
           # Now you can use these variables in other commands
           ID=$(echo "$json" | jq -r '.server')
           # total price from cpu price * cpu amount, ram price * ram amount, storage amount * storage price
           TOTAL_PRICE=$(echo "$CPU_PRICE * $CPU_AMOUNT + $STORAGE_PRICE * $STORAGE_AMOUNT + $RAM_PRICE * $RAM_AMOUNT" | bc -l)
-          echo "ID=$ID" >> "$GITHUB_OUTPUT"
+          echo "ID=$ID" >>"$GITHUB_OUTPUT"
           echo "Total Price: $TOTAL_PRICE"
 
   build-aosp:
@@ -84,9 +94,6 @@ jobs:
         run: |
           sudo apt-get update
           bash setup.sh
-          source ~/.profile
-          cd ~/android/lineage
-          repo init -u https://github.com/LineageOS/android.git -b lineage-22.1 --git-lfs
 
       - name: Clone aosp
         run: |
@@ -140,7 +147,11 @@ jobs:
     steps:
       - name: Provision Machine
         run: |
-          curl --location 'https://marketplace.tensordock.com/api/v0/client/delete/single' \
+          json=$(curl --location 'https://marketplace.tensordock.com/api/v0/client/delete/single' \
             --data-urlencode "api_key=$API_KEY" \
             --data-urlencode "api_token=$API_TOKEN" \
-            --data-urlencode "server=${{ needs.create-machine.outputs.ID }}"
+            --data-urlencode "server=${{ needs.create-machine.outputs.ID }}")
+          if [ "$(echo "$json" | jq -r '.success')" = "false" ]; then
+            echo "Failed to delete server"
+            exit 1
+          fi
